linters:
  disable-all: true
  enable:
    - goimports
    - scopelint
    - gocyclo
    - deadcode
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - bodyclose
    - golint
    - misspell
issues:
  exclude-use-default: false
run:
  deadline: 5m
